{{- if not .Values.cluster.identifier -}}
  {{- fail "ERROR: 'cluster.identifier' is required (e.g. 'prod', 'staging'). Set it via --set cluster.identifier=prod or in values.yaml." -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: runpod-kubelet-config
  namespace: {{ .Values.kubelet.namespace }}
  labels:
    app.kubernetes.io/name: runpod-kubelet-config
    app.kubernetes.io/component: config
data:
  CLUSTER_ID: {{ .Values.cluster.identifier | quote }}
